// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pb_file/product.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductServiceClient is the client API for ProductService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductServiceClient interface {
	GetProdStock(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error)
	// 双向流
	PingPongStream(ctx context.Context, opts ...grpc.CallOption) (ProductService_PingPongStreamClient, error)
}

type productServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductServiceClient(cc grpc.ClientConnInterface) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProdStock(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*OutputResponse, error) {
	out := new(OutputResponse)
	err := c.cc.Invoke(ctx, "/product.ProductService/GetProdStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) PingPongStream(ctx context.Context, opts ...grpc.CallOption) (ProductService_PingPongStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductService_ServiceDesc.Streams[0], "/product.ProductService/pingPongStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &productServicePingPongStreamClient{stream}
	return x, nil
}

type ProductService_PingPongStreamClient interface {
	Send(*InputRequest) error
	Recv() (*OutputResponse, error)
	grpc.ClientStream
}

type productServicePingPongStreamClient struct {
	grpc.ClientStream
}

func (x *productServicePingPongStreamClient) Send(m *InputRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productServicePingPongStreamClient) Recv() (*OutputResponse, error) {
	m := new(OutputResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductServiceServer is the server API for ProductService service.
// All implementations must embed UnimplementedProductServiceServer
// for forward compatibility
type ProductServiceServer interface {
	GetProdStock(context.Context, *InputRequest) (*OutputResponse, error)
	// 双向流
	PingPongStream(ProductService_PingPongStreamServer) error
	mustEmbedUnimplementedProductServiceServer()
}

// UnimplementedProductServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductServiceServer struct {
}

func (UnimplementedProductServiceServer) GetProdStock(context.Context, *InputRequest) (*OutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProdStock not implemented")
}
func (UnimplementedProductServiceServer) PingPongStream(ProductService_PingPongStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PingPongStream not implemented")
}
func (UnimplementedProductServiceServer) mustEmbedUnimplementedProductServiceServer() {}

// UnsafeProductServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductServiceServer will
// result in compilation errors.
type UnsafeProductServiceServer interface {
	mustEmbedUnimplementedProductServiceServer()
}

func RegisterProductServiceServer(s grpc.ServiceRegistrar, srv ProductServiceServer) {
	s.RegisterService(&ProductService_ServiceDesc, srv)
}

func _ProductService_GetProdStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProdStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/product.ProductService/GetProdStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProdStock(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_PingPongStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductServiceServer).PingPongStream(&productServicePingPongStreamServer{stream})
}

type ProductService_PingPongStreamServer interface {
	Send(*OutputResponse) error
	Recv() (*InputRequest, error)
	grpc.ServerStream
}

type productServicePingPongStreamServer struct {
	grpc.ServerStream
}

func (x *productServicePingPongStreamServer) Send(m *OutputResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productServicePingPongStreamServer) Recv() (*InputRequest, error) {
	m := new(InputRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductService_ServiceDesc is the grpc.ServiceDesc for ProductService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProdStock",
			Handler:    _ProductService_GetProdStock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "pingPongStream",
			Handler:       _ProductService_PingPongStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb_file/product.proto",
}
